<xsl:if test="//randernet_duallist_asmselect">
    <script type="text/javascript" src="common/randernet/asmselect/examples/jquery.ui.js"></script>
    <script type="text/javascript" src="common/randernet/asmselect/jquery.asmselect.js"></script>
    <link rel="stylesheet" type="text/css" href="common/randernet/asmselect/jquery.asmselect.css" />
</xsl:if>
<xsl:if test="//randernet_clone_field_container">
    <script type="text/javascript" src="common/randernet/clonefield/jquery.clonefield.js"></script>
</xsl:if>
